frontend:
  stage: test
  interruptible: true
  before_script:
    - bundle config --global jobs "$(nproc)"
    - bundle config --local path 'vendor/gems'

    - "echo -e \"test:\n  adapter: postgresql\n  host: postgres\n  database: ci_test\n  username: runner\n  password: runner\" > config/database.yml"
    - bundle check
    - RAILS_ENV=test bundle exec rails db:test:prepare
  extends: .except
  needs:
    - bundler
  script:
    - cd frontend
    - yarn check --integrity || yarn install
    - yarn playwright install
    - yarn deploy
    - RAILS_ENV=test bundle exec rails s & yarn test
